version: "3.9"
    
services:
  ## MySQL Server
  db:
    image: mysql:5.7
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
    env_file:
      - .env
    # optional
    #restart: always

  ## PHPMyAdmin
  #phpmyadmin:
  #  image: phpmyadmin
  #  ports:
  #    - 127.0.0.1:8080:80
  #  env_file:
  #    - .env
  #  # optional
  #  restart: always
